webApp2/edusponsor/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
]

webApp2/edusponsor/donees/urls.py
from django.conf.urls import url
from . import views

app_name = 'donees'

urlpatterns = [
    url(r'^$', views.donee_list, name="list"),
    url(r'^create/$', views.donee_create, name="create"),
    url(r'^(?P<slug>[\w-]+)/$', views.donee_detail, name="detail"),
]

webApp2/edusponsor/edusponsor/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from donees import views as donee_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^donees/', include('donees.urls')),
    url(r'^about/$', views.about),
    url(r'^studentpage/$', views.studentpage),
    url(r'^$', donee_views.donee_list, name="home"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webApp2/edusponsor/accounts/models.py
from django.db import models

# Create your models here.

webApp2/edusponsor/donees/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class donee(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField()
    message = models.TextField()
    email = models.EmailField()
    contact = models.IntegerField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    def snippet(self):
        return self.message[:150] + '...'

webApp2/edusponsor/donees/forms.py
from django import forms
from . import models

class CreateDonee(forms.ModelForm):
    class Meta:
        model = models.donee
        fields = ['name', 'slug', 'message', 'email', 'contact', 'thumb',]

webApp2/edusponsor/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

def signup_view(request):
    if request.method == 'POST':
         form = UserCreationForm(request.POST)
         if form.is_valid():
             user = form.save()
             #  log the user in
             login(request, user)
             return redirect('donees:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', { 'form': form })

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # log the user in
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
               return redirect('donees:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', { 'form': form })

def logout_view(request):
    if request.method == 'POST':
            logout(request)
            return redirect('donees:list')

webApp2/edusponsor/donees/views.py
from django.shortcuts import render, redirect
from .models import donee
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms



def donee_list(request):
    doneess = donee.objects.all().order_by('date')
    return render(request, 'donees/donee_list.html', {'donees':doneess})


def donee_detail(request, slug):
    # return HttpResponse(slug)
    anyDonee = donee.objects.get(slug=slug)
    return render(request, 'donees/donee_detail.html', {'donee': anyDonee})


@login_required(login_url="/accounts/login/")
def donee_create(request):
    if request.method == 'POST':
        form = forms.CreateDonee(request.POST, request.FILES)
        if form.is_valid():
            # save article to db
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('donees:list')
    else:
        form = forms.CreateDonee()
    return render(request, 'donees/donee_create.html', { 'form': form })

webApp2/edusponsor/edusponsor/views.py
# from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    # return HttpResponse('homepage')
    return render(request, 'homepage.html')

def about(request):
    # return HttpResponse('about')
    return render(request, 'about.html')

def studentpage(request):
    return render(request,'studentpage.html')

webApp2/edusponsor/accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="container">
    <h1>Log in</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}" />
        {% endif %}
        <input class="submit" type="submit" value="Login" />
    </form>
    <p>Not got an account? <a href="{% url 'accounts:signup' %}">Sign Up</a></p>
</div>
{% endblock %}

webApp2/edusponsor/accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="container">
    <h1>Signup</h1>
    <form class="site-form" action="{% url 'accounts:signup' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input class="submit" type="submit" value="Signup">
    </form>
</div>
{% endblock %}

webApp2/edusponsor/donees/templates/donees/donee_create.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="main-display">
<div class="donee-container"
    <div class="create-donee">
        <h2>Write your Story</h2>
        <form class="site-form" action="{% url 'donees:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input class="submit" type="submit" value="Create">
        </form>
    </div>
</div>
</div>
{% endblock %}

webApp2/edusponsor/donees/templates/donees/donee_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<style>
      .SkulPic {
        height:auto ;
        float: right;
        width: auto;
        border-radius:auto ;
        margin-right: 15px;
        margin: 30px;
        max-width: 450px;
        border-color: antiquewhite;
        border-width: 10px;
        border-style: solid;
      }
</style>
<div class="main-display">
<div class="donee-container">
<div class="donee-detail">
    <h2>{{ donee.name }}</h2>
    <img class='SkulPic' src="{{donee.thumb.url}}"/>
    <p class='des'>{{ donee.message }}</p>
    <br></br>
    <p class='email'>{{ donee.email }}</p>
    {% comment %} <a href=("mailto:"+{{donee.email}}) class='email'>{{ donee.email }}</a> {% endcomment %}
    <p class='contact'>{{ donee.contact }}</p>
    <p class='date'>{{ donee.date }}</p>
</div>
</div>
<a class="toTop" href="#">Jump to top</a>
</div>
{% endblock %}
 

webApp2/edusponsor/donees/templates/donees/donee_list.html
{% extends 'base_layout.html' %}
{% block content %}
<div class="main-display">
    <div class="h1-container">
    <h1>Donees List</h1>
    </div>
    <div class="donees">
        {% for donee in donees%}
            <div class="donee">
                <h2><a class="interactive" href="{% url 'donees:detail' slug=donee.slug %}">{{donee.name}}</a></h2>
                <p class='des'>{{ donee.snippet }}</p>
                <p class='email'>{{ donee.email }}</p>
                <p class='contact'>{{ donee.contact }}</p>
                <p class='date'>{{ donee.date }}</p>
            </div>
        {%endfor%}
    </div>
    <a class="toTop" href="#">Jump to top</a>
</div>
{% endblock %}

webApp2/edusponsor/templates/about.html
{% extends 'base_layout.html' %} {% block content %}
<div class="main-display">
<div class="about-container">
<div class="h1-container">
<h1>About Us</h1>
</div>
<img id="P1" src="/static/tumblr_mhti9jYY2m1rboj6jo1_500.jpg" alt="..." />
<p>
  The pandemic that is ravaging the world over, has not been any less disruptive
  for the students and teaching facility across the Nation. In light of the fact
  that the country is being affected by this pandemic , causing even more misery
  and suffering to the underprivileged. In Kenya most underprivileged students
  are faced with a lot of Challenges for example Lack of proper uniform,
  expensive textbooks and for Higher education levels, exorbitant fees
  structures. To put this into perspective 42% of children under 18 live in
  monetarily poor households. As Swami Vivekananda once said, "Education is the
  movement from darkness to light". Imagine being in the dark for more than a
  year.
</p>
 
<p>
  Nearly 1 in 3 children live in households lacking the minimum of nationally
  agreed financial resources and are deprived of a minimum of 3 or more basic
  needs and services. 23% of children are multidimensionally poor even though
  they live in households that are not monetarily poor, indicating that there
  are issues with service accessibility, affordability, and availability.
  Orphans, children with disability, children in rural areas, and those who have
  more siblings are more likely to be multidimensionally poor. Children residing
  in communities that do not have access to basic services like healthcare – in
  terms of distance – are more likely to be multidimensionally poor Children
  residing in areas that experience climatic shocks are more likely to be
  multidimensionally poor.
</p>
<h3>How We Help</h3>
<style>
  #ks2 {
    width: 500px;
    float: left;
    margin-right: 15px;
  }
  #P1 {
    width: auto;
    float: right;
    margin-right: 15px;
  }
</style>
<img id="ks2" src="/static/kenyan-students.jpg" alt="..." />
<p>
  In order to support the underprivileged, we have devised a revolutionary
  website that will provide a stage to voice the needs of our future world
  leaders, engineers, doctors and computer scientists. Our core idea is to
  connect the fortunate and the misfortunate to help each other be the best of
  version of themselves. This is conveyed by letting schools, churches,
  children's homes and boarding schools to express their necessities for a
  better learning experience. On the other hand, the generous people, enjoy the
  heart-warming moments where their small contribution helped someone immensely.
</p>
 
<p>
  Secondly, with the current pandemic the necessity of online education has
  increased through our donor platform not only funding can be provided but also
  various other resources can be provided to support and improve the
  accessibility of information, e.g., Online courses, devices for online
  education etc. The key reason as to why our project will be a success and what
  makes our solution special is the journey that the user will enjoy and the
  connection between the donor and receiver provided via our platform. Together
  with the vast applicability of the project is beyond anyone's thinking.
</p>
 
<a class="toTop" href="#">Jump to top</a>
</div>
</div>
{% endblock %}

webApp2/edusponsor/templates/base_layout.html
 <!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Donees</title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Oswald:wght@200&display=swap" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
        <link rel="stylesheet" href="/static/style.css">
    </head>
    <body>
        <header class="wrapper">
            <h1><a href="{% url 'home' %}"><img id="logo" src="/static/logo.png" alt="edusponsor"/></a></h1>
            <nav>
                <ul class='nav'>
                <li><a href="/studentpage">Student Page</a></li>
                <li><a href="/about">About Us</a></li>
                <li><a href="mailto:edusponsors.info@gmail.com">Email Us</a></li>
                    {% if user.is_authenticated %}
                    <li>
                        <form action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button class="logout-link" type="submit">Logout</button>
                        </form>
                    </li>
                    <li><a href="{% url 'donees:create'%}" class="highlight">New Story</a></li>
                    {% else %}
                        <li><a href="{% url 'accounts:login'%}">Login</a></li>
                        <li><a href="{% url 'accounts:signup'%}">Signup</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <div class="wrapper">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

webApp2/edusponsor/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Homepage</title>
</head>
<body>
    <h1>This is the Homepage</h1>
    <p>Welcome to Edusponsor</p>
</body>
</html>

webApp2/edusponsor/templates/studentpage.html
{% extends 'base_layout.html' %} {% block content %}
<div class="main-display">
    <style>
        .subjectPicture {
            width: 320px;
            float: none ;
            margin-bottom: 15px;
        }
        .subjectContainer{
            padding: 10px;
            border: 3px solid #1d697c;
            position: relative;
            padding-bottom: 40px;
            background-color: #002944;
        }
        .subjectMain {
            display: grid;
            grid-template-columns: 1fr 1fr 1fr;
            grid-gap: 30px;
        }
        
    </style>
    <div class="h1-container">
    <h1 >Welcome To the Students Page!</h1>
    </div>
<div class="subjectMain">
<div class="subjectContainer">
   <h5>Physics</h5>
   <img class="subjectPicture" src="/static/pngegg.png" alt="">
   <p><a href="https://www.physicsclassroom.com/" target="_blank">PhysicsClassroom Links</a></p>
   <p><a href="https://www.physicsandmathstutor.com/" target="_blank">Physics & Math Tutor</a></p>
    
</div>
<div class="subjectContainer">
    <h5>Biology</h5>
    <img class="subjectPicture" src="/static/pngegg (4).png" alt="">
    <p><a href="https://www.pbs.org/wgbh/nova/labs/" target="_blank">Nova Labs</a></p>
    <p><a href="www.easyelimu.com/" target="_blank">Easy Elimu</a></p>
     
 </div>
 <div class="subjectContainer">
    <h5>Coding</h5>
    <img class="subjectPicture" src="/static/pngegg (2).png" alt="">
    <p><a href="https://www.w3schools.com/" target="_blank">W3Schools</a></p>
    <p><a href="https://codewithmosh.com" target="_blank">Mosh Hemadani Tutorials</a></p>
     
 </div>
 <div class="subjectContainer">
    <h5>maths</h5>
    <img class="subjectPicture" src="/static/pngegg (3).png" alt="">
    <p><a href="https://www.mathnation.com/" target="_blank">Math Nation</a></p>
    <p><a href="https://www.mathsisfun.com/" target="_blank">Math is Fun</a></p>
     
 </div>
 <div class="subjectContainer">
    <h5>General Sciences</h5>
    <img class="subjectPicture" src="/static/pngegg (1).png" alt="">
    <p><a href="https://phet.colorado.edu/" target="_blank">Colarado Education</a></p>
    <p><a href="https://www.britannica.com" target="_blank">Britannica</a></p>
     
 </div>
 <div class="subjectContainer">
    <h5>English</h5>
    <img class="subjectPicture" src="/static/pngegg (6).png" alt="">
    <p><a href="https://www.advance-africa.co" target="_blank">Advance Africa</a></p>
    <p><a href="https://cliffsnotes.com/" target="_blank">Cliff Notes</a></p>
     
 </div>
</div>
<a class="toTop" href="#">Jump to top</a>
</div>
</div>
{% endblock %}